# -*- coding: utf-8 -*-
"""Netflix Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1almm5L89y4AVGx4TLoq6ziza5Tq1j-XX
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import datetime as dt

# Load Dataset
df = pd.read_csv("netflix_titles.csv")
df.head()

# Basic Info
df.info()

# Check for nulls
df.isnull().sum()

# Fill or Drop nulls
df['director'] = df['director'].fillna('Not Available')
df['cast'] = df['cast'].fillna('Not Available')
df.dropna(subset=['country', 'date_added'], inplace=True)

# Movie vs TV Show count
sns.countplot(data=df, x='type', palette='Set2')
plt.title("Content Type Distribution")
plt.show()

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

# Content added by year
sns.histplot(data=df, x='year_added', hue='type', multiple='stack')
plt.title("Content Added Over the Years")
plt.show()

# Top 10 genres
from collections import Counter
genres = df['listed_in'].str.split(', ')
genre_counts = Counter([genre for sublist in genres for genre in sublist])
top_genres = pd.DataFrame(genre_counts.most_common(10), columns=['Genre', 'Count'])

sns.barplot(data=top_genres, y='Genre', x='Count', palette='pastel')
plt.title("Top 10 Genres on Netflix")
plt.show()

top_countries = df['country'].value_counts().head(10)
top_countries.plot(kind='bar', color='salmon')
plt.title("Top 10 Countries by Content")
plt.ylabel("Number of Titles")
plt.show()

text = " ".join(df['description'])
wordcloud = WordCloud(width=800, height=400, background_color='black').generate(text)

plt.figure(figsize=(10,5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis('off')
plt.title("Common Words in Descriptions")
plt.show()

!pip install streamlit
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

st.set_page_config(page_title="Netflix Analysis", layout="wide")
st.title("📺 Netflix Content Analysis Dashboard")

# Load Dataset
df = pd.read_csv("netflix_titles.csv")

# Fill or Drop nulls
df['director'] = df['director'].fillna('Not Available')
df['cast'] = df['cast'].fillna('Not Available')
df.dropna(subset=['country', 'date_added'], inplace=True)

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df.dropna(subset=['date_added'], inplace=True) # Drop rows where date_added couldn't be parsed
df['year_added'] = df['date_added'].dt.year

tab1, tab2 = st.tabs(["📈 Trends", "📍 Content Distribution"])

with tab1:
    st.subheader("Content Over Years")
    year_chart = df['year_added'].value_counts().sort_index()
    st.line_chart(year_chart)

    st.subheader("Movie vs TV Shows")
    st.bar_chart(df['type'].value_counts())

with tab2:
    st.subheader("Top Countries")
    st.write(df['country'].value_counts().head(10))

    st.subheader("Top Genres")
    genre_list = df['listed_in'].str.split(', ')
    genres = [genre for sublist in genre_list.dropna() for genre in sublist]
    genre_series = pd.Series(genres).value_counts().head(10)
    st.bar_chart(genre_series)

